#!/usr/bin/env groovy
openshift.withCluster() {
    env.NAMESPACE = openshift.project()
    env.APPLICATION_NAME = 'database-provision-apb'
    echo "Starting Pipeline for ${APPLICATION_NAME}..."
}

pipeline {
    agent {
        label 'widget-jenkins-agent'
    }
    stages {
        stage('configure build') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject(NAMESPACE) {
                            openshift.process(readFile("${env.PROVISIONER_CONTEXT_DIR}/provisioner-build.yaml"))
                        }
                    }
                }
                dir(env.PROVISIONER_CONTEXT_DIR) {
                    sh """
                        oc process -f provisioner-build.yaml | oc apply -f-
                        apb bundle prepare
                    """
                }
            }
        }
        stage('build apb') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject(NAMESPACE) {
                            openshift.selector("bc", "${APPLICATION_NAME}").startBuild().logs("-f")
                        }
                    }
                }
                sh """
                    apb bundle list -v
                    apb broker catalog -v
                    apb broker bootstrap -v
                    apb broker catalog -v
                """
            }
        }
    }
}