#!/usr/bin/env groovy

pipeline {
    agent {
        label 'widget-jenkins-agent'
    }
    stages {
        stage('configure build') {
            steps {
                dir(env.PROVISIONER_CONTEXT_DIR) {
                    sh """
                        oc apply -f provisioner-build.yaml
                    """
                }
            }
        }
        stage('build apb') {
            steps {
                sh """
                    oc start-build -F bc/database-provision-apb
                    apb broker list
                """
            }
        }
    }
}