FROM registry.access.redhat.com/openshift3/jenkins-slave-base-rhel7:latest

# Adapted from Red Hat Community of Practice
# https://github.com/redhat-cop/containers-quickstarts/blob/master/jenkins-slaves/jenkins-slave-ansible/Dockerfile.rhel7

LABEL name="widget-jenkins-agent" \
      version="3.11" \
      architecture="x86_64" \
      release="1" \
      io.k8s.display-name="Widget Jenkins Agent" \
      io.openshift.tags="openshift,jenkins,ansible,oc"

ENV ANSIBLE_VERSION=2.5.8 \
    ANSIBLE_REVISION=1

RUN INSTALL_PKGS="apb ansible" && \
    yum install -y --setopt=tsflags=nodocs \
      --disablerepo=* \
      --enablerepo=rhel-7-server-rpms --enablerepo=rhel-7-server-extras-rpms \
      --enablerepo=rhel-7-server-ansible-2.6-rpms --enablerepo=rhel-7-server-ose-3.11-rpms \
      $INSTALL_PKGS && \
    ansible --version && \
    apb version && \
    sed -n -e '/local_/ p' /etc/ansible/ansible.cfg && \
    echo "local_tmp = /tmp/.ansible/" >> /etc/ansible/ansible.cfg && \
    yum clean all -y && \
    rm -rf /var/cache/yum

USER 1001