#!/usr/bin/env groovy

pipeline {
    agent {
        label 'maven'
    }
    stages {
        stage('configure build') {
            steps {
                dir(env.BUILDER_CONTEXT_DIR) {
                    sh """
                        oc process -f builder.yaml | oc apply -f-
                    """
                }
            }
        }
        stage('build agent') {
            steps {
                sh """
                    oc start-build -F bc/widget-jenkins-agent
                """
            }
        }
    }
}