#!/usr/bin/env groovy
openshift.withCluster() {
    env.NAMESPACE = openshift.project()
    env.APPLICATION_NAME = 'widget-jenkins-agent'
    echo "Starting Pipeline for ${APPLICATION_NAME}..."
}

pipeline {
    agent {
        label 'maven'
    }
    stages {
        stage('configure build') {
            steps {
                dir(env.BUILDER_CONTEXT_DIR) {
                    sh """
                        oc process -f builder.yml \
                            --param=SOURCE_REF=${env.SOURCE_REF} \
                            --param=SOURCE_REPOSITORY_URL=${env.APPLICATION_SOURCE_REPOSITORY_URL} \
                            | oc apply -f-
                    """
                }
            }
        }
        stage('build agent') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject(NAMESPACE) {
                            openshift.selector("bc", "${APPLICATION_NAME}").startBuild().logs("-f")
                            // TODO verify succesful build
                        }
                    }
                }
            }
        }
    }
}