= OpenShift-Ansible Integration Lab

== 0 Introduction

=== 0.1 Usecase

Today we are building a WIDGET inventory tracking system. It comprises of a simple
data driven application backed by MySQL. We will be deploying the application on OpenShift
and the database server on a RHEL virtual machine. 

=== 0.2 Ansible and OpenShift

The goal of this lab is to show how the [OpenShift Container Platform](https://docs.openshift.com/container-platform/latest/getting_started/index.html)
and [Ansible Automation](https://www.ansible.com/resources/get-started) can build on
each other to increase innovation and accelerate delivery.

First we'll introduce how Ansible can be used to automate provisioning and configuration
of application dependencies. Then we'll look at how we can leverage Ansible for application
configuration within OpenShift as part of a pipeline. Finally, we will dig into how the
[OpenShift Ansible Broker](https://docs.openshift.com/container-platform/3.11/architecture/service_catalog/ansible_service_broker.html)
adds self-service automation to the platform.

== 1 Install MySQL Server with Ansible Engine

=== 1.1 Introduction to Ansible

=== 1.2 Review Playbook

=== 1.3 Set up Job Template

=== 1.4 Provision MySQL server on VM

== 2 Deploy Application

`$ oc new-project widget-factory`

=== 2.1 Auto-deploy Jenkins (Template Service Broker)

https://docs.openshift.com/container-platform/3.10/install_config/configuring_pipeline_execution.html

=== 2.2 Configure `widget-jenkins-agent`

```
$ git checkout section-2
$ cd ../widget-jenkins-agent
$ oc process -f widget-pipeline.yaml -p section-2 | oc apply -f-
```

=== 2.3 Review Application

```
$ oc secrets new generic mysql --from-generic=username=dummy --from-generic=password=dummy
```

=== 2.4 Ansible-Applier

=== 2.5 Deploy Application

== 3 Connect Application to MySQL

=== 3.1 Review Legacy Solution

=== 3.2 Automation Service Broker

=== 3.3 Build an APB

```
$ git checkout section-3
$ cd ../database-provision-apb

...

$ oc new-build --binary=true --name database-provision-apb
$ oc policy add-role-to-user system:image-builder system:serviceaccount:widget-factory:builder -n openshift
$ oc patch bc/database-provision-apb -p '{"spec": {"output":{"to": {"namespace": "openshift" } } } }'

...

$ apb bundle prepare
$ oc start-build --follow --from-dir . database-provision-apb
$ apb broker bootstrap
```

=== 3.4 Provision Database and Credentials

=== 3.5 Update Application to Use Bindings